config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sales
  resources :products
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  helper :all
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = 'El producto se creó exitosamente.'
      redirect_to @product 
    else
      flash[:error] = 'Ocurrió un error al guardar el producto'
      render :new 
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    if @product.update(product_params)
      flash[:success] = 'El producto se actualizó exitosamente.'
      redirect_to @product
    else
      flash[:error] = 'Ocurrió un error al guardar los cambios'
      render :edit
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    flash[:success] = 'El producto fué borrado exitosamente.'
    redirect_to products_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :reference, :description, :price)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:description, :total_price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Haz iniciado sesión!!"
    else
      flash.now[:error] = "Alguno de los datos ingresados es incorrecto, intentalo nuevamente!"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Hasta la próxima!!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="col-sm-6 col-sm-offset-3" style="margin-top:15%;">
<% if current_user %>

<% else %>  
  <div class="panel panel-default">
    <div class="panel-heading text-center">
      <h4>Bienvenido!</h4>
    </div>
    <div class="panel-body text-center">
      <div id="main-container" class="container-fluid">
        <div class="row">
          <div class="btn-group"> 
            <%= link_to 'Iniciar sesión', login_path, :class => "btn btn-success" %>
          </div>
        <div>
      <div>
    </div>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
      <div class="alert alert-info" role="alert" >
            <%= value %>
      </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">Inicio</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Productos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Lista de productos', products_path %></li>
            <li><%= link_to 'Crear producto', new_product_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Importar productos</a></li>
         </ul>
       </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ventas <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Lista de ventas', sales_path %></li>
            <li><%= link_to 'Crear venta', new_sale_path %></li>
         </ul>
       </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to 'Cerrar sesión', logout_path %></li>
      <% end %>
    </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hardware Store</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <% if current_user %>
      <%= render "layouts/header" %>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="main-container" class="container-fluid">
    <div class="row">
      <div id="main-content" class="col-xs-6">
        <form accept-charset="UTF-8" action="/product" class="new_product" id="new_product" method="post">
          <div class="form-group">
            <label for="product_name">Nombre</label>
            <input class="form-control" id="product_name" name="product[name]" value=<%= @product.name %>>
          </div>
          <div class="form-group">
            <label for="product_reference">Código de barras</label>
            <input class="form-control" id="product_reference" name="product[reference]" value=<%= product.reference %>>
          </div>
          <div class="form-group">
            <label for="product_description">Descripción</label>
            <textarea class="form-control" id="product_description" name="product[description]" ><%= @product.description %></textarea>
          </div>
          <div class="form-group">
            <label for="product_price">Precio</label>
            <input class="form-control" id="product_price" name="product[price]" value=<%= @product.price %>>
          </div>
          <div class="btn-group">
            <% if @product.id %>
              <input class="btn btn-success" name="commit" type="submit" value="Guardar">
            <% else %>
              <input class="btn btn-success" name="commit" type="submit" value="Crear">
            <% end %>
            <%= link_to 'Cancelar', products_path, :class => "btn btn-default" %>
          </div>
        </form>
      <div>
    <div>
  <div>
<% end %>

app/views/products/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Inicio' %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Productos', products_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= link_to @product.name, @product %></li>
    <li class="breadcrumb-item" aria-current="page">Editar</li>
  </ol>
</nav>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Inicio' %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Productos', products_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Listado</li>
  </ol>
</nav>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Codigo de barras</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Precio</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr scope="row">
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.reference %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Ver', product, :class => "btn btn-default" %>
            <%= link_to 'Editar', edit_product_path(product), :class => "btn btn-default" %>
            <%= link_to 'Borrar', product, method: :delete, data: { confirm: 'Estas seguro que queres borrar este producto?' }, :class => "btn btn-danger" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="btn-group">
  <%= link_to 'Crear producto', new_product_path, :class => "btn btn-default" %>
</div>
<br>

app/views/products/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Inicio' %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Productos', products_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Nuveo producto</li>
  </ol>
</nav>
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<% if flash[:success] %>
  <div class="alert alert-success"><%= flash[:success] %></div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Inicio' %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Productos', products_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @product.name %></li>
  </ol>
</nav>
<p id="notice"><%= notice %></p>
<div id="main-container" class="container-fluid">
  <div class="row">
    <div id="main-content" class="col-xs-6">
      <form accept-charset="UTF-8" action="/product" class="new_product" id="new_product">
        <div class="form-group">
          <label for="product_name">Nombre</label>
          <input class="form-control" id="product_name" name="product[name]" value=<%= @product.name %> disabled>
        </div>
        <div class="form-group">
          <label for="product_reference">Código de barras</label>
          <input class="form-control" id="product_reference" name="product[reference]" value=<%= @product.reference %> disabled>
        </div>
        <div class="form-group">
          <label for="product_description">Descripción</label>
          <textarea class="form-control" id="product_description" name="product[description]" disabled><%= @product.description %></textarea>
        </div>
        <div class="form-group">
          <label for="product_price">Precio</label>
          <input class="form-control" id="product_price" name="product[price]" value=<%= @product.price %> disabled>
        </div>
        <div class="btn-group">
          <%= link_to 'Editar', edit_product_path(@product), :class => "btn btn-default" %>
          <%= link_to 'Atras', products_path, :class => "btn btn-default" %>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Descripción' %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label 'Total' %>
    <%= form.text_field :total_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ventas</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Descripción</th>
      <th scope="col">Total</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr scope="row">
        <td><%= sale.description %></td>
        <td><%= sale.total_price %></td>
        <td><%= link_to 'Ver', sale %></td>
        <td><%= link_to 'Editar', edit_sale_path(sale) %></td>
        <td><%= link_to 'Borrar', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva venta', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripción:</strong>
  <%= @sale.description %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sale.total_price %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>